esphome:
  name: correlation-analyzer
  includes:
    - correlation-analysis/main.h
    - correlation-analysis/config.h
  libraries:
    - Preferences

esp32:
  board: esp32dev
  framework:
    type: arduino

mqtt:
  broker: !secret mqtt_broker

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "535fc1de44ed9f80a8c656e684e7d34a"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Convolution-Analyzer"
    password: "vHCFVzmsnbLm"

captive_portal:

binary_sensor:
  - platform: custom
    lambda: |-
      auto sound_sensor = new SoundSensorCorr();
      App.register_component(sound_sensor);
      return {sound_sensor->sound_recognition_sensor_corr};
  
    binary_sensors:
      name: "Doorbell sensor"