esphome:
  name: dwt-analyzer
  platform: ESP32
  board: esp32dev
  includes:
    - dwt_analysis/main.h
  libraries:
    - wavelib=https://github.com/rafat/wavelib.git

mqtt:
  broker: !secret mqtt_broker
  # username: !secret mqtt_user
  # password: !secret mqtt_password

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "8c8c226b4e9207939601da6a6182326a"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "DWT-Analyzer Fallback Hotspot"
    password: "OZPDjBEO7QfA"

captive_portal:

binary_sensor:
  - platform: custom
    lambda: |-
      auto dwt_sensor = new DWTSensor();
      App.register_component(dwt_sensor);
      return {dwt_sensor};

    binary_sensors:
      name: "DWT Sensor"