esphome:
  name: fourier-analyzer
  platform: ESP32
  board: esp32dev
  includes:
    - fourier-analysis/main.h
    - fourier-analysis/config.h
  libraries:
    - arduinoFFT=https://github.com/zverbikadam/arduinoFFT.git#esphome

mqtt:
  broker: !secret mqtt_broker
  # username: !secret mqtt_user
  # password: !secret mqtt_password

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "8c8c226b4e9207939601da6a6182326a"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Sound-Analyzer Fallback Hotspot"
    password: "OZPDjBEO7QfA"

captive_portal:

binary_sensor:
  - platform: custom
    lambda: |-
      auto sound_sensor = new SoundSensorFFT();
      App.register_component(sound_sensor);
      return {sound_sensor->sound_recognition_sensor_fft};

    binary_sensors:
      name: "Sound Sensor"
