esphome:
  name: sound-analyzer
  platform: ESP32
  board: esp32dev
  includes:
    - sound_recognition/sound_analysis.h
    - sound_recognition/main.h
  libraries:
    - "kosme/arduinoFFT"

mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_user
  password: !secret mqtt_password

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "8c8c226b4e9207939601da6a6182326a"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Sound-Analyzer Fallback Hotspot"
    password: "OZPDjBEO7QfA"

captive_portal:

binary_sensor:
  - platform: custom
    lambda: |-
      auto sound_sensor = new SoundSensor();
      App.register_component(sound_sensor);
      return {sound_sensor};

    binary_sensors:
      name: "Sound Sensor"